DEFAULT_MODELS = [
    {
        "provider": "openrouter",
        "model_id": "openai/gpt-4o-mini",
        "display_name": "GPT-4o Mini",
        "capabilities_json": {"label": "balanced", "strengths": ["general", "chat"]},
        "context_window": 128000,
        "supports_streaming": True,
        "supports_tools": True,
        "input_cost_per_1m": 0.15,
        "output_cost_per_1m": 0.60,
        "fallback_model_id": "google/gemini-flash-1.5",
        "is_active": True,
    },
    {
        "provider": "openrouter",
        "model_id": "anthropic/claude-3.5-sonnet",
        "display_name": "Claude Sonnet",
        "capabilities_json": {"label": "reasoning", "strengths": ["writing", "analysis"]},
        "context_window": 200000,
        "supports_streaming": True,
        "supports_tools": True,
        "input_cost_per_1m": 3.0,
        "output_cost_per_1m": 15.0,
        "fallback_model_id": "openai/gpt-4o-mini",
        "is_active": True,
    },
    {
        "provider": "openrouter",
        "model_id": "google/gemini-flash-1.5",
        "display_name": "Gemini Flash",
        "capabilities_json": {"label": "fast", "strengths": ["speed", "low latency"]},
        "context_window": 1000000,
        "supports_streaming": True,
        "supports_tools": False,
        "input_cost_per_1m": 0.075,
        "output_cost_per_1m": 0.30,
        "fallback_model_id": "deepseek/deepseek-chat",
        "is_active": True,
    },
    {
        "provider": "openrouter",
        "model_id": "deepseek/deepseek-chat",
        "display_name": "DeepSeek Chat",
        "capabilities_json": {"label": "low cost", "strengths": ["cost", "coding"]},
        "context_window": 64000,
        "supports_streaming": True,
        "supports_tools": False,
        "input_cost_per_1m": 0.14,
        "output_cost_per_1m": 0.28,
        "fallback_model_id": "openai/gpt-4o-mini",
        "is_active": True,
    },
]

