import uuid
from datetime import datetime
from sqlalchemy import DateTime, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database import Base

class User(Base):
    __tablename__ = "users"

    # Primary unique identifier for the user.
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # Unique email address used for login.
    email: Mapped[str] = mapped_column(String(320), unique=True, index=True, nullable=False)
    # Password hash generated by the configured password hasher.
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    # Timestamp when the account was created.
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    # Timestamp when the account was last updated.
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    # Optional personal portfolio URL for future profile context.
    portfolio_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    # Optional GitHub URL for future profile context.
    github_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    # Optional LinkedIn URL for future profile context.
    linkedin_url: Mapped[str | None] = mapped_column(String(500), nullable=True)

    conversations = relationship("Conversation", back_populates="user", cascade="all, delete-orphan")
